<?php

namespace Database\Seeders;

use App\Models\IofCompany;
use Illuminate\Database\Seeder;

class IofcompanySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $records = [
            [
                'id' => 1,
                'type' => '3',
                'precedence' => 1,
                'systemId' => '43',
                'shortName' => 'Agni Systems Limited',
                'fullName' => 'Agni Systems Limited',
                'status' => 1,
                'user_id' => 1,
                'created_at' => '2021-01-10 11:33:38',
                'updated_at' => '2021-02-28 11:44:09',
            ],
            [
                'id' => 2,
                'type' => '3',
                'precedence' => 2,
                'systemId' => '38',
                'shortName' => 'Bangla ICX Ltd.',
                'fullName' => 'Bangla ICX Ltd.',
                'status' => 1,
                'user_id' => 1,
                'created_at' => '2021-01-10 11:34:42',
                'updated_at' => '2021-01-10 11:34:42',
            ],
            [
                'id' => 3,
                'type' => '3',
                'precedence' => 3,
                'systemId' => '55',
                'shortName' => 'Bangla Telecom Limited',
                'fullName' => 'Bangla Telecom Limited',
                'status' => 1,
                'user_id' => 1,
                'created_at' => '2021-01-10 11:35:25',
                'updated_at' => '2021-01-10 11:35:25',
            ],
            [
                'id' => 4,
                'type' => '3',
                'precedence' => 4,
                'systemId' => '26',
                'shortName' => 'Bangladesh Telecommunications Company Limited',
                'fullName' => 'Bangladesh Telecommunications Company Limited',
                'status' => 1,
                'user_id' => 1,
                'created_at' => '2021-01-10 11:35:56',
                'updated_at' => '2021-01-10 11:35:56',
            ],
            [
                'id' => 5,
                'type' => '3',
                'precedence' => 5,
                'systemId' => '36',
                'shortName' => 'Bantel Limited',
                'fullName' => 'Bantel Limited',
                'status' => 1,
                'user_id' => 1,
                'created_at' => '2021-01-10 11:36:51',
                'updated_at' => '2021-02-28 11:44:59',
            ],
            [
                'id' => 6,
                'type' => '3',
                'precedence' => 6,
                'systemId' => '37',
                'shortName' => 'Cloud Tel Limited',
                'fullName' => 'Cloud Tel Limited',
                'status' => 1,
                'user_id' => 1,
                'created_at' => '2021-01-10 11:37:33',
                'updated_at' => '2021-01-10 11:37:33',
            ],
            [
                'id' => 7,
                'type' => '3',
                'precedence' => 7,
                'systemId' => '50',
                'shortName' => 'Gazi Networks Limited',
                'fullName' => 'Gazi Networks Limited',
                'status' => 1,
                'user_id' => 1,
                'created_at' => '2021-01-10 11:38:03',
                'updated_at' => '2021-01-10 11:38:03',
            ],
            [
                'id' => 8,
                'type' => '3',
                'precedence' => 8,
                'systemId' => '32',
                'shortName' => 'Getco Telecommunications Limited',
                'fullName' => 'Getco Telecommunications Limited',
                'status' => 1,
                'user_id' => 1,
                'created_at' => '2021-01-10 11:38:42',
                'updated_at' => '2021-01-10 11:38:42',
            ],
            [
                'id' => 9,
                'type' => '3',
                'precedence' => 9,
                'systemId' => '40',
                'shortName' => 'Imam Network Ltd.',
                'fullName' => 'Imam Network Ltd.',
                'status' => 1,
                'user_id' => 1,
                'created_at' => '2021-01-10 11:39:16',
                'updated_at' => '2021-01-10 11:39:16',
            ],
            [
                'id' => 10,
                'type' => '3',
                'precedence' => 10,
                'systemId' => '41',
                'shortName' => 'Integrated Services Limited',
                'fullName' => 'Integrated Services Limited',
                'status' => 1,
                'user_id' => 1,
                'created_at' => '2021-01-10 11:39:48',
                'updated_at' => '2021-01-10 11:39:48',
            ],
            [
                'id' => 11,
                'type' => '3',
                'precedence' => 11,
                'systemId' => '47',
                'shortName' => 'Jibondhara Solutions Ltd.',
                'fullName' => 'Jibondhara Solutions Ltd.',
                'status' => 1,
                'user_id' => 1,
                'created_at' => '2021-01-10 11:40:26',
                'updated_at' => '2021-01-10 11:40:26',
            ],
            [
                'id' => 12,
                'type' => '3',
                'precedence' => 12,
                'systemId' => '33',
                'shortName' => 'M & H Telecom',
                'fullName' => 'M & H Telecom',
                'status' => 1,
                'user_id' => 1,
                'created_at' => '2021-01-10 11:40:55',
                'updated_at' => '2021-01-10 11:40:55',
            ],
            [
                'id' => 13,
                'type' => '3',
                'precedence' => 13,
                'systemId' => '53',
                'shortName' => 'M. M. Communications Ltd.',
                'fullName' => 'M. M. Communications Ltd.',
                'status' => 1,
                'user_id' => 1,
                'created_at' => '2021-01-10 11:41:33',
                'updated_at' => '2021-01-10 11:41:33',
            ],
            [
                'id' => 14,
                'type' => '3',
                'precedence' => 14,
                'systemId' => '51',
                'shortName' => 'Micro Trade',
                'fullName' => 'Micro Trade',
                'status' => 1,
                'user_id' => 1,
                'created_at' => '2021-01-10 11:42:07',
                'updated_at' => '2021-01-10 11:42:07',
            ],
            [
                'id' => 15,
                'type' => '3',
                'precedence' => 15,
                'systemId' => '42',
                'shortName' => 'Mother Telecommunication',
                'fullName' => 'Mother Telecommunication',
                'status' => 1,
                'user_id' => 1,
                'created_at' => '2021-01-10 11:42:36',
                'updated_at' => '2021-01-10 11:42:36',
            ],
            [
                'id' => 16,
                'type' => '3',
                'precedence' => 16,
                'systemId' => '44',
                'shortName' => 'New Generation Telecom Limited',
                'fullName' => 'New Generation Telecom Limited',
                'status' => 1,
                'user_id' => 1,
                'created_at' => '2021-01-10 11:43:02',
                'updated_at' => '2021-01-10 11:43:02',
            ],
            [
                'id' => 17,
                'type' => '3',
                'precedence' => 17,
                'systemId' => '34',
                'shortName' => 'Paradise Telecom Ltd.',
                'fullName' => 'Paradise Telecom Ltd.',
                'status' => 1,
                'user_id' => 1,
                'created_at' => '2021-01-10 11:43:28',
                'updated_at' => '2021-01-10 11:43:28',
            ],
            [
                'id' => 18,
                'type' => '3',
                'precedence' => 18,
                'systemId' => '49',
                'shortName' => 'Purple Telecom Limited',
                'fullName' => 'Purple Telecom Limited',
                'status' => 1,
                'user_id' => 1,
                'created_at' => '2021-01-10 11:43:53',
                'updated_at' => '2021-01-10 11:43:53',
            ],
            [
                'id' => 19,
                'type' => '3',
                'precedence' => 19,
                'systemId' => '48',
                'shortName' => 'RingTech (Bangladesh) Ltd.',
                'fullName' => 'RingTech (Bangladesh) Ltd.',
                'status' => 1,
                'user_id' => 5,
                'created_at' => '2021-01-10 11:44:28',
                'updated_at' => '2021-03-11 06:17:12',
            ],
            [
                'id' => 20,
                'type' => '3',
                'precedence' => 20,
                'systemId' => '54',
                'shortName' => 'S R Telecom Limited',
                'fullName' => 'S R Telecom Limited',
                'status' => 1,
                'user_id' => 1,
                'created_at' => '2021-01-10 11:45:15',
                'updated_at' => '2021-01-10 11:45:15',
            ],
            [
                'id' => 21,
                'type' => '3',
                'precedence' => 21,
                'systemId' => '46',
                'shortName' => 'Crossworld Telecom Limited',
                'fullName' => 'Crossworld Telecom Limited',
                'status' => 1,
                'user_id' => 1,
                'created_at' => '2021-01-10 11:46:51',
                'updated_at' => '2021-01-10 11:46:51',
            ],
            [
                'id' => 22,
                'type' => '3',
                'precedence' => 22,
                'systemId' => '45',
                'shortName' => 'Softex Communication Limited',
                'fullName' => 'Softex Communication Limited',
                'status' => 1,
                'user_id' => 1,
                'created_at' => '2021-01-10 11:47:20',
                'updated_at' => '2021-01-10 11:47:20',
            ],
            [
                'id' => 23,
                'type' => '3',
                'precedence' => 23,
                'systemId' => '52',
                'shortName' => 'Tele Exchange Limited',
                'fullName' => 'Tele Exchange Limited',
                'status' => 1,
                'user_id' => 1,
                'created_at' => '2021-01-10 11:47:49',
                'updated_at' => '2021-01-10 11:47:49',
            ],
            [
                'id' => 24,
                'type' => '3',
                'precedence' => 24,
                'systemId' => '35',
                'shortName' => 'Teleplus Newyork Limited',
                'fullName' => 'Teleplus Newyork Limited',
                'status' => 1,
                'user_id' => 1,
                'created_at' => '2021-01-10 11:48:26',
                'updated_at' => '2021-01-10 11:48:26',
            ],
            [
                'id' => 25,
                'type' => '3',
                'precedence' => 25,
                'systemId' => '56',
                'shortName' => 'Summit Communications Limited',
                'fullName' => 'Summit Communications Limited',
                'status' => 1,
                'user_id' => 1,
                'created_at' => '2021-01-10 11:48:56',
                'updated_at' => '2021-01-10 11:48:56',
            ],
            [
                'id' => 26,
                'type' => '3',
                'precedence' => 26,
                'systemId' => '39',
                'shortName' => 'VOICETEL LTD.',
                'fullName' => 'VOICETEL LTD.',
                'status' => 1,
                'user_id' => 1,
                'created_at' => '2021-01-10 11:49:25',
                'updated_at' => '2021-02-28 05:26:22',
            ],
            [
                'id' => 27,
                'type' => '4',
                'precedence' => 1,
                'systemId' => '57',
                'shortName' => 'Grameenphone Limited',
                'fullName' => 'Grameenphone Limited',
                'status' => 1,
                'user_id' => 1,
                'created_at' => '2021-01-10 11:52:53',
                'updated_at' => '2021-01-10 11:52:53',
            ],
            [
                'id' => 28,
                'type' => '4',
                'precedence' => 2,
                'systemId' => '59',
                'shortName' => 'Robi Axiata Limited',
                'fullName' => 'Robi Axiata Limited',
                'status' => 1,
                'user_id' => 1,
                'created_at' => '2021-01-10 11:53:42',
                'updated_at' => '2021-01-10 11:53:42',
            ],
            [
                'id' => 29,
                'type' => '4',
                'precedence' => 3,
                'systemId' => '58',
                'shortName' => 'Banglalink Digital Communications Ltd.',
                'fullName' => 'Banglalink Digital Communications Ltd.',
                'status' => 1,
                'user_id' => 1,
                'created_at' => '2021-01-10 11:54:13',
                'updated_at' => '2021-01-10 11:54:13',
            ],
            [
                'id' => 30,
                'type' => '4',
                'precedence' => 4,
                'systemId' => '60',
                'shortName' => 'Airtel Bangladesh Ltd.',
                'fullName' => 'Airtel Bangladesh Ltd.',
                'status' => 1,
                'user_id' => 1,
                'created_at' => '2021-01-10 11:54:54',
                'updated_at' => '2021-01-12 04:38:39',
            ],
            [
                'id' => 31,
                'type' => '2',
                'precedence' => 1,
                'systemId' => '3680',
                'shortName' => 'Bangla Trac Communications Limited',
                'fullName' => 'Bangla Trac Communications Limited',
                'status' => 1,
                'user_id' => 1,
                'created_at' => '2021-01-10 11:56:31',
                'updated_at' => '2021-01-10 11:56:31',
            ],
            [
                'id' => 32,
                'type' => '2',
                'precedence' => 2,
                'systemId' => '245',
                'shortName' => 'Bangladesh Telecommunications Company Limited',
                'fullName' => 'Bangladesh Telecommunications Company Limited',
                'status' => 1,
                'user_id' => 1,
                'created_at' => '2021-01-10 11:57:09',
                'updated_at' => '2021-01-10 11:57:09',
            ],
            [
                'id' => 33,
                'type' => '2',
                'precedence' => 3,
                'systemId' => '3686',
                'shortName' => 'Digicon Telecommunication Limited',
                'fullName' => 'Digicon Telecommunication Limited',
                'status' => 1,
                'user_id' => 1,
                'created_at' => '2021-01-10 11:57:34',
                'updated_at' => '2021-01-10 11:57:34',
            ],
            [
                'id' => 34,
                'type' => '2',
                'precedence' => 4,
                'systemId' => '3684',
                'shortName' => 'Global Voice Telecom Limited',
                'fullName' => 'Global Voice Telecom Limited',
                'status' => 1,
                'user_id' => 1,
                'created_at' => '2021-01-10 11:58:00',
                'updated_at' => '2021-01-10 11:58:00',
            ],
            [
                'id' => 35,
                'type' => '2',
                'precedence' => 5,
                'systemId' => '3681',
                'shortName' => 'Mir Telecom Limited',
                'fullName' => 'Mir Telecom Limited',
                'status' => 1,
                'user_id' => 1,
                'created_at' => '2021-01-10 11:58:37',
                'updated_at' => '2021-01-10 11:58:37',
            ],
            [
                'id' => 36,
                'type' => '2',
                'precedence' => 6,
                'systemId' => '3683',
                'shortName' => 'NovoTel Limited',
                'fullName' => 'NovoTel Limited',
                'status' => 1,
                'user_id' => 1,
                'created_at' => '2021-01-10 11:59:11',
                'updated_at' => '2021-01-10 11:59:11',
            ],
            [
                'id' => 37,
                'type' => '2',
                'precedence' => 7,
                'systemId' => '3679',
                'shortName' => 'Roots Communication Limited',
                'fullName' => 'Roots Communication Limited',
                'status' => 1,
                'user_id' => 1,
                'created_at' => '2021-01-10 11:59:37',
                'updated_at' => '2021-01-10 11:59:37',
            ],
            [
                'id' => 38,
                'type' => '2',
                'precedence' => 8,
                'systemId' => '3685',
                'shortName' => 'Unique Infoway Limited',
                'fullName' => 'Unique Infoway Limited',
                'status' => 1,
                'user_id' => 1,
                'created_at' => '2021-01-10 12:00:00',
                'updated_at' => '2021-01-10 12:00:00',
            ],
            [
                'id' => 39,
                'type' => '4',
                'precedence' => 5,
                'systemId' => '62',
                'shortName' => 'Teletalk Bangladesh Limited',
                'fullName' => 'Teletalk Bangladesh Limited',
                'status' => 1,
                'user_id' => 1,
                'created_at' => '2021-01-12 04:38:15',
                'updated_at' => '2021-01-12 04:38:15',
            ],
            [
                'id' => 40,
                'type' => '4',
                'precedence' => 6,
                'systemId' => '61',
                'shortName' => 'Pacific Bangladesh Telecom Limited (Citycell)',
                'fullName' => 'Pacific Bangladesh Telecom Limited (Citycell)',
                'status' => 1,
                'user_id' => 1,
                'created_at' => '2021-01-12 04:39:14',
                'updated_at' => '2021-01-12 04:39:14',
            ],
            // Add more records in the same format...
            [
                'id' => 41,
                'type' => '4',
                'precedence' => 7,
                'systemId' => '63',
                'shortName' => 'Bangladesh Telecommunications Company Limited (BTCL)',
                'fullName' => 'Bangladesh Telecommunications Company Limited (BTCL)',
                'status' => 1,
                'user_id' => 1,
                'created_at' => '2021-01-12 04:41:12',
                'updated_at' => '2021-01-12 04:41:12',
            ],
            [
                'id' => 42,
                'type' => '4',
                'precedence' => 8,
                'systemId' => '84',
                'shortName' => 'ADN Telecom Limited',
                'fullName' => 'ADN Telecom Limited',
                'status' => 1,
                'user_id' => 1,
                'created_at' => '2021-01-12 04:41:40',
                'updated_at' => '2021-01-12 04:41:40',
            ],
            [
                'id' => 43,
                'type' => '4',
                'precedence' => 9,
                'systemId' => '80',
                'shortName' => 'Agni System Limited',
                'fullName' => 'Agni System Limited',
                'status' => 1,
                'user_id' => 1,
                'created_at' => '2021-01-12 04:42:09',
                'updated_at' => '2021-01-12 04:42:09',
            ],
            [
                'id' => 44,
                'type' => '4',
                'precedence' => 10,
                'systemId' => '68',
                'shortName' => 'Bangla Phone Limited',
                'fullName' => 'Bangla Phone Limited',
                'status' => 1,
                'user_id' => 1,
                'created_at' => '2021-01-12 04:42:41',
                'updated_at' => '2021-01-12 04:42:41',
            ],
            [
                'id' => 45,
                'type' => '4',
                'precedence' => 11,
                'systemId' => '106',
                'shortName' => 'BDCOM Online Limited',
                'fullName' => 'BDCOM Online Limited',
                'status' => 1,
                'user_id' => 1,
                'created_at' => '2021-01-12 04:43:09',
                'updated_at' => '2021-01-12 04:43:09',
            ],
            [
                'id' => 46,
                'type' => '4',
                'precedence' => 12,
                'systemId' => '83',
                'shortName' => 'Bangladesh Export Import Company Limited',
                'fullName' => 'Bangladesh Export Import Company Limited',
                'status' => 1,
                'user_id' => 1,
                'created_at' => '2021-01-12 04:43:33',
                'updated_at' => '2021-01-12 04:43:33',
            ],
            [
                'id' => 47,
                'type' => '4',
                'precedence' => 13,
                'systemId' => '75',
                'shortName' => 'Business Technology Solutions ( BTS)',
                'fullName' => 'Business Technology Solutions ( BTS)',
                'status' => 1,
                'user_id' => 1,
                'created_at' => '2021-01-12 04:44:14',
                'updated_at' => '2021-01-12 04:44:14',
            ],
            [
                'id' => 48,
                'type' => '4',
                'precedence' => 14,
                'systemId' => '85',
                'shortName' => 'Amber IT Limited',
                'fullName' => 'Amber IT Limited',
                'status' => 1,
                'user_id' => 1,
                'created_at' => '2021-01-12 04:44:41',
                'updated_at' => '2021-01-12 04:44:41',
            ],
            [
                'id' => 49,
                'type' => '4',
                'precedence' => 15,
                'systemId' => '78',
                'shortName' => 'Fusion Net limited',
                'fullName' => 'Fusion Net limited',
                'status' => 1,
                'user_id' => 1,
                'created_at' => '2021-01-12 04:45:47',
                'updated_at' => '2023-09-11 03:55:30',
            ],
            [
                'id' => 50,
                'type' => '4',
                'precedence' => 16,
                'systemId' => '87',
                'shortName' => 'HRC Technologies Limited( IPTSP)',
                'fullName' => 'HRC Technologies Limited( IPTSP)',
                'status' => 1,
                'user_id' => 1,
                'created_at' => '2021-01-12 04:46:50',
                'updated_at' => '2021-01-12 04:46:50',
            ],
            [
                'id' => 51,
                'type' => '4',
                'precedence' => 17,
                'systemId' => '111',
                'shortName' => 'Idea Net',
                'fullName' => 'Idea Net',
                'status' => 1,
                'user_id' => 1,
                'created_at' => '2021-01-12 04:47:34',
                'updated_at' => '2021-01-12 04:47:34',
            ],
            [
                'id' => 52,
                'type' => '4',
                'precedence' => 18,
                'systemId' => '115',
                'shortName' => 'InterCloud Limited',
                'fullName' => 'InterCloud Limited',
                'status' => 1,
                'user_id' => 1,
                'created_at' => '2021-01-12 04:48:02',
                'updated_at' => '2021-01-12 04:48:02',
            ],
            [
                'id' => 53,
                'type' => '4',
                'precedence' => 19,
                'systemId' => '108',
                'shortName' => 'Link3 Technologies Ltd.',
                'fullName' => 'Link3 Technologies Ltd.',
                'status' => 1,
                'user_id' => 1,
                'created_at' => '2021-01-12 04:48:31',
                'updated_at' => '2021-01-12 04:48:31',
            ],
            [
                'id' => 54,
                'type' => '4',
                'precedence' => 20,
                'systemId' => '86',
                'shortName' => 'MetroNet Bangladesh Limited',
                'fullName' => 'MetroNet Bangladesh Limited',
                'status' => 1,
                'user_id' => 1,
                'created_at' => '2021-01-12 04:48:59',
                'updated_at' => '2021-01-12 04:48:59',
            ],
            [
                'id' => 55,
                'type' => '4',
                'precedence' => 21,
                'systemId' => '88',
                'shortName' => 'Next One',
                'fullName' => 'Next One',
                'status' => 1,
                'user_id' => 1,
                'created_at' => '2021-01-12 04:49:31',
                'updated_at' => '2021-01-12 04:49:31',
            ],
            [
                'id' => 56,
                'type' => '4',
                'precedence' => 22,
                'systemId' => '65',
                'shortName' => 'Ranks Telecom Ltd',
                'fullName' => 'Ranks Telecom Ltd',
                'status' => 1,
                'user_id' => 1,
                'created_at' => '2021-01-12 04:50:49',
                'updated_at' => '2021-01-12 04:52:03',
            ],
            [
                'id' => 57,
                'type' => '4',
                'precedence' => 23,
                'systemId' => '0',
                'shortName' => 'Roaming Call',
                'fullName' => 'Roaming Call',
                'status' => 1,
                'user_id' => 1,
                'created_at' => '2021-01-12 04:51:15',
                'updated_at' => '2021-01-12 04:51:15',
            ],
            [
                'id' => 58,
                'type' => '4',
                'precedence' => 24,
                'systemId' => '91',
                'shortName' => 'RANKSITT-IPTSP',
                'fullName' => 'RANKSITT-IPTSP',
                'status' => 1,
                'user_id' => 1,
                'created_at' => '2021-01-12 04:51:47',
                'updated_at' => '2021-01-12 04:51:47',
            ],
            [
                'id' => 59,
                'type' => '4',
                'precedence' => 25,
                'systemId' => '109',
                'shortName' => 'CONNECTBD',
                'fullName' => 'CONNECTBD',
                'status' => 1,
                'user_id' => 1,
                'created_at' => '2021-01-12 04:52:37',
                'updated_at' => '2021-01-12 04:52:37',
            ],
            [
                'id' => 60,
                'type' => '4',
                'precedence' => 26,
                'systemId' => '76',
                'shortName' => 'Information Service Network(ISN)',
                'fullName' => 'Information Service Network(ISN)',
                'status' => 1,
                'user_id' => 1,
                'created_at' => '2021-01-12 04:53:11',
                'updated_at' => '2021-01-12 04:53:11',
            ],
            [
                'id' => 61,
                'type' => '4',
                'precedence' => 27,
                'systemId' => '116',
                'shortName' => 'Telebangla IPTSP',
                'fullName' => 'Telebangla IPTSP',
                'status' => 1,
                'user_id' => 1,
                'created_at' => '2021-01-12 04:53:37',
                'updated_at' => '2021-01-12 04:53:37',
            ],
            [
                'id' => 62,
                'type' => '4',
                'precedence' => 28,
                'systemId' => '117',
                'shortName' => 'BracNet IPTSP',
                'fullName' => 'BracNet IPTSP',
                'status' => 1,
                'user_id' => 1,
                'created_at' => '2021-01-12 04:54:23',
                'updated_at' => '2021-01-12 04:54:23',
            ],
            [
                'id' => 63,
                'type' => '4',
                'precedence' => 29,
                'systemId' => 'DigiCon',
                'shortName' => 'DigiCon IPTSP',
                'fullName' => 'DigiCon IPTSP',
                'status' => 1,
                'user_id' => 1,
                'created_at' => '2021-01-12 04:56:05',
                'updated_at' => '2021-02-28 11:48:11',
            ],
            [
                'id' => 64,
                'type' => '4',
                'precedence' => 30,
                'systemId' => '119',
                'shortName' => 'SSD-TECH',
                'fullName' => 'SSD-TECH',
                'status' => 1,
                'user_id' => 1,
                'created_at' => '2021-01-12 04:56:57',
                'updated_at' => '2021-01-12 04:56:57',
            ],
            [
                'id' => 65,
                'type' => '4',
                'precedence' => 31,
                'systemId' => '92',
                'shortName' => 'RoyalGreen IPTSP',
                'fullName' => 'RoyalGreen IPTSP',
                'status' => 1,
                'user_id' => 1,
                'created_at' => '2021-01-12 04:57:54',
                'updated_at' => '2021-01-12 04:57:54',
            ],
            [
                'id' => 66,
                'type' => '1',
                'precedence' => 1,
                'systemId' => '10',
                'shortName' => '1Asia Alliance Gateway Limited',
                'fullName' => '1Asia Alliance Gateway Limited',
                'status' => 1,
                'user_id' => 1,
                'created_at' => '2021-01-12 05:01:05',
                'updated_at' => '2023-09-24 11:20:20',
            ],
            [
                'id' => 67,
                'type' => '1',
                'precedence' => 2,
                'systemId' => '22',
                'shortName' => 'Bangla Tel Limited',
                'fullName' => 'Bangla Tel Limited',
                'status' => 1,
                'user_id' => 1,
                'created_at' => '2021-01-12 05:01:57',
                'updated_at' => '2021-01-12 05:01:57',
            ],
            [
                'id' => 68,
                'type' => '1',
                'precedence' => 3,
                'systemId' => '2',
                'shortName' => 'Bangla Trac Communications Limited',
                'fullName' => 'Bangla Trac Communications Limited',
                'status' => 1,
                'user_id' => 1,
                'created_at' => '2021-01-12 05:02:39',
                'updated_at' => '2021-01-12 05:02:39',
            ],
            [
                'id' => 69,
                'type' => '1',
                'precedence' => 4,
                'systemId' => '7',
                'shortName' => 'BG Tel Limited',
                'fullName' => 'BG Tel Limited',
                'status' => 1,
                'user_id' => 1,
                'created_at' => '2021-01-12 05:03:07',
                'updated_at' => '2021-01-12 05:03:07',
            ],
            [
                'id' => 70,
                'type' => '1',
                'precedence' => 5,
                'systemId' => '26',
                'shortName' => 'Bangladesh International Gateway Limited',
                'fullName' => 'Bangladesh International Gateway Limited',
                'status' => 1,
                'user_id' => 1,
                'created_at' => '2021-01-12 05:03:51',
                'updated_at' => '2021-02-28 11:52:14',
            ],

            [
                'id' => 71,
                'type' => '1',
                'precedence' => 6,
                'systemId' => '3',
                'shortName' => 'Bangladesh Telecommunications Company Limited',
                'fullName' => 'Bangladesh Telecommunications Company Limited',
                'status' => 1,
                'user_id' => 1,
                'created_at' => '2021-01-12 05:04:39',
                'updated_at' => '2021-01-12 05:04:39',
            ],
            [
                'id' => 72,
                'type' => '1',
                'precedence' => 7,
                'systemId' => '20',
                'shortName' => 'Cel Telecom Limited',
                'fullName' => 'Cel Telecom Limited',
                'status' => 1,
                'user_id' => 1,
                'created_at' => '2021-01-12 05:05:14',
                'updated_at' => '2021-01-12 05:05:14',
            ],
            [
                'id' => 73,
                'type' => '1',
                'precedence' => 8,
                'systemId' => '14',
                'shortName' => 'DBL Telecom Limited',
                'fullName' => 'DBL Telecom Limited',
                'status' => 1,
                'user_id' => 1,
                'created_at' => '2021-01-12 05:05:39',
                'updated_at' => '2021-01-12 05:05:39',
            ],
            [
                'id' => 74,
                'type' => '1',
                'precedence' => 9,
                'systemId' => '27',
                'shortName' => 'Digicon Telecommunication Limited',
                'fullName' => 'Digicon Telecommunication Limited',
                'status' => 1,
                'user_id' => 1,
                'created_at' => '2021-01-12 05:06:11',
                'updated_at' => '2021-01-12 05:06:11',
            ],
            [
                'id' => 75,
                'type' => '1',
                'precedence' => 10,
                'systemId' => '16',
                'shortName' => 'First Communication Limited',
                'fullName' => 'First Communication Limited',
                'status' => 1,
                'user_id' => 1,
                'created_at' => '2021-01-12 05:06:56',
                'updated_at' => '2021-01-12 05:06:56',
            ],
            [
                'id' => 76,
                'type' => '1',
                'precedence' => 11,
                'systemId' => '6',
                'shortName' => 'Global Voice Telecom Limited',
                'fullName' => 'Global Voice Telecom Limited',
                'status' => 1,
                'user_id' => 1,
                'created_at' => '2021-01-12 05:07:21',
                'updated_at' => '2021-01-12 05:07:21',
            ],
            [
                'id' => 77,
                'type' => '1',
                'precedence' => 12,
                'systemId' => '8',
                'shortName' => 'HRC Technologies Limited',
                'fullName' => 'HRC Technologies Limited',
                'status' => 1,
                'user_id' => 1,
                'created_at' => '2021-01-12 05:07:37',
                'updated_at' => '2021-01-12 05:07:37',
            ],
            [
                'id' => 78,
                'type' => '1',
                'precedence' => 13,
                'systemId' => '118',
                'shortName' => 'LR Telecom Limited',
                'fullName' => 'LR Telecom Limited',
                'status' => 1,
                'user_id' => 1,
                'created_at' => '2021-01-12 05:07:53',
                'updated_at' => '2021-01-12 05:07:53',
            ],
            [
                'id' => 79,
                'type' => '1',
                'precedence' => 14,
                'systemId' => '4',
                'shortName' => 'Mir Telecom Limited',
                'fullName' => 'Mir Telecom Limited',
                'status' => 1,
                'user_id' => 1,
                'created_at' => '2021-01-12 05:08:16',
                'updated_at' => '2021-01-12 05:08:16',
            ],
            [
                'id' => 80,
                'type' => '1',
                'precedence' => 15,
                'systemId' => '19',
                'shortName' => 'MOS5 Tel Limited',
                'fullName' => 'MOS5 Tel Limited',
                'status' => 1,
                'user_id' => 1,
                'created_at' => '2021-01-12 05:08:34',
                'updated_at' => '2021-02-28 10:25:53',
            ],
            [
                'id' => 81,
                'type' => '1',
                'precedence' => 16,
                'systemId' => '5',
                'shortName' => 'NovoTel Limited',
                'fullName' => 'NovoTel Limited',
                'status' => 1,
                'user_id' => 1,
                'created_at' => '2021-01-12 05:08:56',
                'updated_at' => '2021-01-12 05:08:56',
            ],
            [
                'id' => 82,
                'type' => '1',
                'precedence' => 17,
                'systemId' => '24',
                'shortName' => 'Platinum Communications Limited',
                'fullName' => 'Platinum Communications Limited',
                'status' => 1,
                'user_id' => 1,
                'created_at' => '2021-01-12 05:09:17',
                'updated_at' => '2021-01-12 05:09:17',
            ],
            [
                'id' => 83,
                'type' => '1',
                'precedence' => 18,
                'systemId' => '21',
                'shortName' => 'Ranks Telecom Limited',
                'fullName' => 'Ranks Telecom Limited',
                'status' => 1,
                'user_id' => 1,
                'created_at' => '2021-01-12 05:09:36',
                'updated_at' => '2021-01-12 05:09:36',
            ],
            [
                'id' => 84,
                'type' => '1',
                'precedence' => 19,
                'systemId' => '9',
                'shortName' => 'Roots Communication Limited',
                'fullName' => 'Roots Communication Limited',
                'status' => 1,
                'user_id' => 1,
                'created_at' => '2021-01-12 05:09:54',
                'updated_at' => '2021-01-12 05:09:54',
            ],
            [
                'id' => 85,
                'type' => '1',
                'precedence' => 20,
                'systemId' => '12',
                'shortName' => 'Sigma Telecom Limited',
                'fullName' => 'Sigma Telecom Limited',
                'status' => 1,
                'user_id' => 1,
                'created_at' => '2021-01-12 05:10:12',
                'updated_at' => '2021-01-12 05:10:12',
            ],
            [
                'id' => 86,
                'type' => '1',
                'precedence' => 21,
                'systemId' => '23',
                'shortName' => 'SM Communication Limited',
                'fullName' => 'SM Communication Limited',
                'status' => 1,
                'user_id' => 1,
                'created_at' => '2021-01-12 05:10:35',
                'updated_at' => '2021-01-12 05:10:35',
            ],
            [
                'id' => 87,
                'type' => '1',
                'precedence' => 22,
                'systemId' => '30',
                'shortName' => 'Songbird Telecom Limited',
                'fullName' => 'Songbird Telecom Limited',
                'status' => 1,
                'user_id' => 1,
                'created_at' => '2021-01-12 05:10:54',
                'updated_at' => '2021-01-12 05:10:54',
            ],
            [
                'id' => 88,
                'type' => '1',
                'precedence' => 23,
                'systemId' => '11',
                'shortName' => 'Unique Infoway Limited',
                'fullName' => 'Unique Infoway Limited',
                'status' => 1,
                'user_id' => 1,
                'created_at' => '2021-01-12 05:11:15',
                'updated_at' => '2021-01-12 05:11:15',
            ],
            [
                'id' => 89,
                'type' => '1',
                'precedence' => 24,
                'systemId' => '28',
                'shortName' => 'Venus Telecom Limited',
                'fullName' => 'Venus Telecom Limited',
                'status' => 1,
                'user_id' => 1,
                'created_at' => '2021-01-12 05:11:34',
                'updated_at' => '2021-01-12 05:11:34',
            ],
        ];

        // Insert the records into the database
        foreach ($records as $data) {
            IofCompany::create($data);
        }

    }
}
