<?php
namespace App\Authors;

class AuthorInformation {

    public static function authors(): array
    {
        return [
            'creator' 		=> 'Mohammad Shah Alam (shaha2266@gmail.com)',
            'sTitle' 		=> 'Oneclick reporting system',
            'sSubject' 		=> 'Office 365 XLSX Daily Reports',
            'sDescription' 	=> 'This report is auto-generated by the Oneclick reporting system. This system developed by Mohammad Shah Alam',
            'sKeywords' 	=> 'MS Office 365, Laravel 8.54, PHP 7.3, MSSQL, PhpOffice, Laravel Excel',
            'sCategory' 	=> 'Reports',
        ];
    }
}
